### ISSUE TITLE
Showroom section // success stories in news section?

### ISSUE THREAD

**Issue by Guite** [zikula/zikula.org#37]
Should we feature references on the website?
If yes, how to decide which are added and which not?
How can we ensure they are regularly maintained?

Also consider a news category for _success stories_. Maybe this would be better than just having a list of URLs. A success story could also contain images and maybe even a video.

**Comment by Kaik** [comment]
Nice, I think we may consider using something like 
1. Hardcoded cases when we know it will stay or we will take care of checking because we want to have those/any -  on website highlighted 
2. An expiration date for others etc... in see more section etc... 

The decision, well hard to say but probably some kind of voting for hardcoded...  
Anyway, I think we should have it we could wait until we have 3-4 good cases then we should promote those.

**Comment by Guite** [comment]
Here are some of ours: https://guite.de/en/referenzen-und-beispiele.html
